openapi: "3.0.3"
info: 
  version: "3.0.0"
  title: "메일매일"
  description: "메인 기능 api입니다."
servers:
  - url: http://localhost:3000/
paths:
  $ref: './paths/_index.yaml'
components:
  $ref: './components/_index.yaml'
